# Generated by Django 3.0.4 on 2020-05-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_track_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
