# Generated by Django 3.0.4 on 2020-05-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_customer_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.Business'),
        ),
    ]
