# Generated by Django 3.0.4 on 2020-05-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0006_auto_20200502_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='openpay_status_number',
        ),
        migrations.AddField(
            model_name='order',
            name='shippping_cost',
            field=models.FloatField(default=0),
        ),
    ]
