# Generated by Django 3.0.4 on 2020-05-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_auto_20200502_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('period', models.IntegerField(choices=[(0, 'Days'), (1, 'Month'), (2, 'Year')])),
                ('period_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
