# Generated by Django 3.0.4 on 2020-06-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0010_auto_20200628_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('openpay', 'OpenPay'), ('paypal', 'PayPal'), ('cash', 'Cash')], default=2, max_length=155),
        ),
    ]
