# Generated by Django 3.0.4 on 2020-06-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0011_auto_20200628_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippping_cost',
            new_name='shipping_cost',
        ),
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('openpay', 'OpenPay'), ('paypal', 'PayPal'), ('cash', 'Cash')], default='cash', max_length=155),
        ),
    ]
